services:
  app:
    image: ${ZIL_APP_IMAGE:-docker.io/truchekaterina/zil-app:lab7}
    container_name: zil-app
    restart: unless-stopped
    depends_on: []
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
      SPRING_PROFILES_ACTIVE: docker
      DBHOST: ${DBHOST:-hl12.zil}
      DBPORT: ${DBPORT:-5433}
      DBNAME: ${DBNAME:-hl7}
      SCHEMANAME: ${SCHEMANAME:-hl7}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-hl7}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-hl7}
      SERVER_TOMCAT_THREADS_MAX: ${SERVER_TOMCAT_THREADS_MAX:-200}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL:-false}
    ports:
      - "${APP_HOST_PORT:-8083}:8083"
    deploy:
      resources:
        limits:
          cpus: "${APP_CPUS:-1.0}"
          memory: ${APP_MEM:-1024M}
